This is a combination of 5 big commits. 1. Archived old files to archive folder in AlphaToBeta_synced folder. 2. Inside run_AtoB_gpu.sh:     1. Added cd /storage/aditya/AlphaMut-master/AlphaToBeta_synced at line 60 for going to the directory before        running the AlphaToBeta.py python script in run_AtoB_gpu.sh file in AlphaToBeta_synced folder. Translated the same        change to run_AtoB_gpu.sh file in AlphaToBeta_local folder.     2. Added #SBATCH --exclusive for exclusive node access.     3. #SBATCH --ntasks-per-node=1 from --ntasks-per-node=2 to specify only 1 task per node. Because each node mean a        single GPU for this case. And a single A30 only has 23.50 GiB memory which is not sufficient for 2 tasks as a        single task takes 11.73 GiB memory approximately.     4. Changed #SBATCH --gres=gpu:1 from #SBATCH --gres=gpu:2 to allocate only 1 GPU per node. As multiple GPU allocation might cause errors.     Translated the same changes to run_AtoB_gpu.sh file in AlphaToBeta_local folder.
3. Inside environment.py in Helix_in_protein_with_neigh folder:
    While reciving the reward output from the reward.py file in environment.py inside Helix_in_protein_with_neigh folder, unpacked the output into reward and
    aa_counts to fix error: (basically stable_baselines3 expects reward to be a single float value, not a tuple)
    File "/home/aditya/mambaforge/envs/AlphaToBeta/lib/python3.9/site-packages/stable_baselines3/common/monitor.py", line 95, in step
    self.rewards.append(float(reward))
    TypeError: float() argument must be a string or a number, not 'tuple'
    Translated the same changes to environment.py AlphaToBeta_local folders.

4. Inside reward.py in Helix_in_protein_with_neigh folder:
    1. While validating the residue indices at line 166 instead of checking if starting_residue and ending_residue
        are instances of python int, checked if they are instances of Integral from numbers module. Because
        isinstance(starting_residue, int) returns False for numpy.int64 type which is a subclass of Integral. And was causing this error:
            File "/storage/aditya/AlphaMut-master/AlphaToBeta_synced/Helix_in_protein_with_neigh/reward.py", line 166,
            in percentage_of_secondary_structure raise TypeError("Residue indices must be integers")
            TypeError: Residue indices must be integers
    2. Added type annotations for get_reward_from_resultant_pct function. I had added plddt calculation value based on the flag use_old_plddt
        (True/False) in the return statement of get_reward_from_resultant_pct function. But had the not updated the funciton calls for
        get_reward_from_resultant_pct function accordingly. Hence, added two function calls each to be called based on the value of use_old_plddt flag.
        and made results_above_plddt_limit optional with default value as none. And fixed this error as result:
            File "/storage/aditya/AlphaMut-master/AlphaToBeta_synced/Helix_in_protein_with_neigh/reward.py", line 566, in reward_function_with_env_counts
            result_plddt=results_above_plddt_limit,
            UnboundLocalError: local variable 'results_above_plddt_limit' referenced before assignment

    3. At line 564, fixed the bug where helix_or_sheet_pct variable was getting used before assignment. As unpacking
        the tuple returned from percentage_of_secondary_structure function was done conditionally. For the cases when helix_or_sheet_pct
        was not getting assigned any value. Hence, used the unpacked varible resultant_a_and_b_percentage instead of helix_or_sheet_pct
        in the function call get_reward_from_resultant_pct.
    Translated the same changes to reward.py file in AlphaToBeta_local folder.

5. Added use_plddt_in_reward=False, argument to env initlization call inside AlphaToBeta.py files in both AlphaToBeta_synced and AlphaToBeta_local folders.